# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_wordEx', '0003_auto_20181011_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='OniondeskMain',
            fields=[
                ('id', models.BigIntegerField(help_text='아이디', primary_key=True, serialize=False)),
                ('subdomain_name', models.CharField(help_text='서브 도메인명 (웹 주소 앞부분)', max_length=50, unique=True)),
                ('host_mapping', models.CharField(blank=True, help_text='호스트 맵핑', max_length=200, null=True)),
                ('owner_email_addr', models.CharField(help_text='계정소유자 이메일 주소', max_length=190, unique=True)),
                ('desk_name', models.CharField(help_text='오니온데스크 이름', max_length=100)),
                ('desk_logo_path', models.CharField(blank=True, help_text='오니온데스크 로고 저장위치', max_length=200, null=True)),
                ('desk_favicon_path', models.CharField(blank=True, help_text='오니온데스크 파비콘 저장위치', max_length=200, null=True)),
                ('desk_theme', models.CharField(default='default', help_text='오니온데스크 테마', max_length=50)),
                ('desk_language', models.CharField(help_text='오니온데스크 기본 언어 (예: ko, en)', max_length=10)),
                ('desk_timezone', models.CharField(help_text='오니온데스크 기본 시간대 (예: Asia/Seoul)', max_length=50)),
                ('desk_date_format', models.CharField(help_text='오니온데스크 날짜 표시형식 (Y.m.d, m.d.Y)', max_length=20)),
                ('desk_home_form_cd', models.CharField(help_text='오니온데스크 홈 표시형식', max_length=2)),
                ('subdomain_changeable_yn', models.CharField(help_text='서브 도메인명 (웹 주소 앞부분) 변경 가능여부 (Y:가능, N:불가능)', max_length=1)),
                ('status_cd', models.CharField(help_text='오니온데스크 상태', max_length=2)),
                ('join_date', models.DateTimeField(help_text='오니온데스크 가입일시')),
                ('out_date', models.DateTimeField(help_text='오니온데스크 탈퇴일시', null=True)),
            ],
            options={
                'db_table': 'oniondesk_main',
            },
        ),
    ]
