# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ip_address',
        ),
    ]
